# Generated by Django 5.0.3 on 2025-01-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardiao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='imagem_identidade',
            field=models.ImageField(blank=True, null=True, upload_to='identidades/'),
        ),
    ]
