# Generated by Django 5.0.3 on 2025-01-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardiao', '0002_cliente_imagem_identidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
