# Generated by Django 5.0.3 on 2025-01-02 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardiao', '0003_material_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='materiais',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='isAtiva',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='EmprestimoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guardiao.emprestimo')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guardiao.material')),
            ],
        ),
    ]
