# Generated by Django 5.0.3 on 2025-01-02 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardiao', '0004_remove_emprestimo_materiais_emprestimo_isativa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='materiais',
            field=models.ManyToManyField(through='guardiao.EmprestimoMaterial', to='guardiao.material'),
        ),
    ]
