# Generated by Django 5.0.3 on 2025-01-03 12:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardiao', '0006_categoria_remove_material_descricao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmprestimoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Ativado', 'Ativado'), ('Desativado', 'Desativado'), ('Reativado', 'Reativado'), ('Cancelado', 'Cancelado')], max_length=50)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='guardiao.emprestimo')),
                ('operador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='guardiao.operador')),
            ],
        ),
    ]
