# Generated by Django 5.0.3 on 2025-01-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardiao', '0007_emprestimohistorico'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='clientes/fotos/'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='isAtivo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='organizacao_militar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
