# Generated by Django 5.0.3 on 2025-01-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardiao', '0008_cliente_cpf_cliente_foto_cliente_isativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operador',
            name='funcao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='operador',
            name='nivel_acesso',
            field=models.IntegerField(choices=[(1, 'Nível 1'), (2, 'Nível 2'), (3, 'Nível 3')], default=1),
        ),
    ]
