# Generated by Django 5.0.3 on 2025-01-03 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardiao', '0011_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assinante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FuncaoAssinante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProntoArmamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('lacre', models.CharField(max_length=50)),
                ('conteudo', models.TextField()),
                ('assinante_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinante_1', to='guardiao.assinante')),
                ('assinante_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinante_2', to='guardiao.assinante')),
                ('assinante_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinante_3', to='guardiao.assinante')),
                ('funcao_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcao_1', to='guardiao.funcaoassinante')),
                ('funcao_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcao_2', to='guardiao.funcaoassinante')),
                ('funcao_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcao_3', to='guardiao.funcaoassinante')),
            ],
        ),
    ]
