# Generated by Django 5.0.3 on 2025-01-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardiao', '0012_assinante_funcaoassinante_prontoarmamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prontoarmamento',
            name='conteudo',
            field=models.JSONField(),
        ),
    ]
