# Generated by Django 5.0.3 on 2025-01-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardiao', '0013_alter_prontoarmamento_conteudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prontoarmamento',
            name='conteudo',
            field=models.TextField(),
        ),
    ]
