# Generated by Django 5.0.3 on 2025-01-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardiao', '0014_alter_prontoarmamento_conteudo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prontoarmamento',
            name='conteudo',
        ),
        migrations.AddField(
            model_name='prontoarmamento',
            name='html_renderizado',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
