# Generated by Django 5.0.3 on 2025-01-04 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guardiao', '0015_remove_prontoarmamento_conteudo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prontoarmamento',
            old_name='html_renderizado',
            new_name='tabelas_html',
        ),
    ]
