# Generated by Django 5.0.3 on 2025-01-04 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guardiao', '0016_rename_html_renderizado_prontoarmamento_tabelas_html'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prontoarmamento',
            old_name='tabelas_html',
            new_name='tabelas',
        ),
    ]
