# Generated by Django 5.0.3 on 2025-01-04 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guardiao', '0017_rename_tabelas_html_prontoarmamento_tabelas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prontoarmamento',
            old_name='tabelas',
            new_name='tabela',
        ),
    ]
